# SECURITY: This file contains sensitive business data
# DO NOT COMMIT TO GITHUB - This file should be in .gitignore

# Main application password
password = "YourMainPasswordHere"

# User passwords (can be revoked by changing these values)
sarah_password = "Sarah2025!"
allison_password = "Allison2025"

# Booth pricing (confidential business data)
booth_prices = {
    "standard_1d": 5000,
    "standard_2d": 7500,
    "platinum": 10000,
    "best_of": 10000,
    "premier": 15000
}

# Add-ons pricing 2025 (confidential business data)
add_ons_2025 = {
    "program_ad_full": {"label": "Program Guide Full Page Ad", "price": 2000},
    "charging_stations": {"label": "In-Person Charging Station", "price": 2000},
    "wifi_sponsorship": {"label": "Wi-Fi Network Sponsorship", "price": 3000},
    "platform_banner": {"label": "Platform Banner Ad", "price": 2000},
    "email_banner": {"label": "Email Banner Ad", "price": 2500},
    "registration_banner": {"label": "Registration Banner Ad", "price": 2000},
    "networking_reception": {"label": "In-Person Networking Reception", "price": 3500},
    "networking_activity": {"label": "Networking Activity / Excursion", "price": 3500},
    "advisory_board": {"label": "Advisory Board (3-hour)", "price": 30000},
    "non_cme_session": {"label": "Non-CME/CE Session (45 min)", "price": 50000}
}

# Add-ons pricing 2026 (confidential business data)
add_ons_2026 = {
    "program_ad_full": {"label": "Program Guide Full Page Ad", "price": 2000},
    "charging_stations": {"label": "In-Person Charging Station", "price": 3000},
    "wifi_sponsorship": {"label": "Wi-Fi Network Sponsorship", "price": 3000},
    "platform_banner": {"label": "Platform Banner Ad", "price": 2000},
    "email_banner": {"label": "Email Banner Ad", "price": 2500},
    "registration_banner": {"label": "Registration Banner Ad", "price": 2000},
    "networking_reception": {"label": "In-Person Networking Reception", "price": 3500},
    "networking_activity": {"label": "Networking Activity / Excursion", "price": 3500},
    "advisory_board": {"label": "Advisory Board (3-hour)", "price": 30000},
    "non_cme_session": {"label": "Non-CME/CE Session (45 min)", "price": 50000}
}
